
FROM node:20-alpine


RUN apk add --no-cache bash curl


WORKDIR /app


COPY package*.json ./

RUN npm install -g npm@11.0.0


RUN npm install


RUN npm audit --audit-level=high


COPY . .


EXPOSE 3000


CMD ["npm", "start"]
